// Syncs en/*.yaml (source of truth) into src/data.ts.
// Usage: npm run content:sync
// Requires the `yaml` dev dependency (npm i -D yaml).
// Note: projects + skills stay curated in this template — only
// profile and experience are regenerated from YAML.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import YAML from "yaml";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const load = (f) => YAML.parse(readFileSync(join(root, "en", f), "utf8"));

const author = load("author.yaml");
const { experience } = load("experience.yaml");

const iconFor = (i) => ["finance", "cloud", "data", "megaphone"][i % 4];
// Short role for the collapsed timeline (drops "Intern", keeps it structured).
const shortRoleFor = (role) =>
  ({
    "AI Engineer Intern": "AI Engineer",
    "ML Engineer Intern": "ML Engineer",
    "ML Research Intern": "ML Researcher",
    "SEO Analytics Intern": "SEO Analytics",
  })[role] ?? role;
// Year-only display, e.g. "May 2025 - Aug 2025" -> "2025"
const yearOf = (period) => (period.match(/20\d{2}/) ? period.match(/20\d{2}/)[0] : period);

const expEntries = experience
  .slice(0, 4)
  .map((job, i) => {
    const bullets = (job.responsibilities ?? [job.description].filter(Boolean))
      .map((b) => `      "${b.replace(/"/g, '\\"')}",`)
      .join("\n");
    return `  {
    company: "${job.company}",
    role: "${job.role}",
    shortRole: "${shortRoleFor(job.role)}",
    date: "${yearOf(job.period)}${job.country ? ` · ${job.country}` : ""}",
    shortDate: "${yearOf(job.period)}",
    icon: "${iconFor(i)}" as const,
    bullets: [
${bullets}
    ],
  },`;
  })
  .join("\n");

const out = `// GENERATED by npm run content:sync from en/*.yaml — edit the YAML, then re-run.
// (projects + skills stay curated; profile + experience regenerate.)
// CV uses the Drive *view* link so it opens in a new tab (no forced download).
const CV_URL =
  process.env.NEXT_PUBLIC_CV_URL ??
  "https://drive.google.com/file/d/1fzpG-faTi5edqGlsVUmH5Y5ds5XAJgF5/view?usp=sharing";
const GITHUB_USERNAME = process.env.NEXT_PUBLIC_GITHUB_USERNAME ?? "${author.social.github_username}";

const MARGIN_URL = "https://prxshetty.github.io/margin/";

export const profile = {
  name: "${author.name}",
  role: "AI / ML Engineer",
  location: "${author.location}",
  githubUsername: GITHUB_USERNAME,
  bio: "hi there — I'm an AIML engineer based in New York. Right now I'm building Margin, a local-first AI writing studio that keeps everything on your machine.",
  bio2: "Before that I interned at 3 startups — most recently GoodFin (YC), where I built LLM eval and benchmarking systems and led research covered across financial press. My Hugo theme even picked up 100 stars on GitHub, which was a fun surprise.",
  bio3: "I'm currently open to AIML and software engineering roles — if you like my work and would like to talk more, feel free to send me a message.",
  links: {
    x: "${author.social.twitter}",
    github: "${author.social.github}",
    linkedin: "${author.social.linkedin}",
    email: "mailto:${author.social.email}",
    resume: CV_URL,
    margin: MARGIN_URL,
    hugo: "https://themes.gohugo.io/themes/hugo-noir/",
  },
};

export const experience = [
${expEntries}
];

export const education: { degree: string; field: string; school: string; date: string }[] = [];

// Curated — edit directly in src/data.ts.
export const skills = {
  Languages: [
    { name: "Python", href: "https://www.python.org" },
    { name: "TypeScript", href: "https://www.typescriptlang.org" },
    { name: "JavaScript", href: "https://developer.mozilla.org/en-US/docs/Web/JavaScript" },
    { name: "R", href: "https://www.r-project.org" },
  ],
  "AI / ML": [
    { name: "PyTorch", href: "https://pytorch.org" },
    { name: "LangChain", href: "https://www.langchain.com" },
    { name: "LangGraph", href: "https://www.langchain.com/langgraph" },
    { name: "Hugging Face", href: "https://huggingface.co" },
    { name: "OpenAI", href: "https://openai.com" },
  ],
  Data: [
    { name: "Pandas", href: "https://pandas.pydata.org" },
    { name: "PySpark", href: "https://spark.apache.org/docs/latest/api/python" },
    { name: "MongoDB", href: "https://www.mongodb.com" },
    { name: "Supabase", href: "https://supabase.com" },
  ],
  Web: [
    { name: "React", href: "https://react.dev" },
    { name: "Next.js", href: "https://nextjs.org" },
    { name: "Tailwind CSS", href: "https://tailwindcss.com" },
    { name: "Streamlit", href: "https://streamlit.io" },
    { name: "Flask", href: "https://flask.palletsprojects.com" },
    { name: "Node.js", href: "https://nodejs.org" },
    { name: "Docker", href: "https://www.docker.com" },
    { name: "GitHub", href: "https://github.com" },
  ],
};

// Curated best-5 — edit directly in src/data.ts.
export const projects: {
  name: string;
  description: string;
  href: string;
  icon: "paykit" | "superzed" | "hitch" | "opensec";
  youtube?: string;
}[] = [
  {
    name: "Grok Interviews",
    description:
      "3.6M+ curated interview resources and 81K technical questions across 5 domains — scraped by multi-LLM pipelines over 20+ search engines. Live at grokinterviews.org.",
    href: "https://github.com/prxshetty/grokinterviews",
    icon: "paykit" as const,
    youtube: "https://www.youtube.com/watch?v=bCTKYImpETI",
  },
  {
    name: "Margin",
    description:
      "Local-first AI writing studio for storytellers — markdown-native editor, automatic context from characters and lore, diff review, works with local LLMs or your own agent subscription.",
    href: "https://prxshetty.github.io/margin/",
    icon: "superzed" as const,
    youtube: "https://youtu.be/X18DxQ_3ju8?si=Kv5BRzR_pR2ZQKbl",
  },
  {
    name: "Hugo Noir",
    description:
      "Clean, minimal, multilingual Hugo theme built for readability — picked up 100 stars on GitHub.",
    href: "https://themes.gohugo.io/themes/hugo-noir/",
    icon: "hitch" as const,
  },
  {
    name: "Lumi",
    description:
      "BrickHack runner-up — the first voice-controlled Mac agent: 10 custom tools, real-time speech with interruptions, script execution, web search and image gen, all built from scratch in 24h.",
    href: "https://devpost.com/software/lumi-personal-ai-assistant",
    icon: "opensec" as const,
  },
  {
    name: "Critique",
    description:
      "Lightweight, minimal writing assistant for macOS that runs entirely on-device — Swift, MLX, LLM routing, your own API keys.",
    href: "https://prxshetty.github.io/Critique/",
    icon: "paykit" as const,
  },
];
`;

writeFileSync(join(root, "src", "data.ts"), out);
console.log("Synced en/*.yaml -> src/data.ts");
