// GENERATED by npm run content:sync from en/*.yaml — edit the YAML, then re-run.
// (projects + skills stay curated; profile + experience regenerate.)
// CV uses the Drive *view* link so it opens in a new tab (no forced download).
const CV_URL =
  process.env.NEXT_PUBLIC_CV_URL ??
  "https://drive.google.com/file/d/1dWrSL7WFW2tw8-lZRmI0gKawHNmYtba2/view?usp=sharing";
const GITHUB_USERNAME = process.env.NEXT_PUBLIC_GITHUB_USERNAME ?? "prxshetty";

const MARGIN_URL = "https://prxshetty.github.io/margin/";

export const profile = {
  name: "Pranam",
  role: "AI Software Engineer",
  location: "Rochester, NY",
  githubUsername: GITHUB_USERNAME,
  bio: "I'm an Engineer based in New York, with 2+ years of experience building AI, ML, and software systems across professional engineering, open source, and independent projects.",
  bio2: "Most recently, I worked as an AI Engineer at GoodFin, where I built an end-to-end LLM benchmarking and evaluation system for financial reasoning, featured in a live [CNBC](https://drive.google.com/file/d/1mgHM0do_BvjVAWK2H_XLJJLTOmNzYFbU/view). I've also worked on real-time ML systems, distributed data pipelines, software and multimodal models.",
  bio3: "I'm currently building HireMeOrElse, a computer-use browser agent for automating the job search and application process. I've also built [noir](https://themes.gohugo.io/themes/hugo-noir/) and [margin](https://prxshetty.github.io/margin/). If you're interested in my work or think I'd be a good fit for your team, feel free to reach out.",
  links: {
    x: "https://www.twitter.com/pnxshy",
    github: "https://github.com/prxshetty",
    linkedin: "https://www.linkedin.com/in/prxshetty",
    email: "mailto:ps9960@g.rit.edu",
    resume: CV_URL,
    margin: MARGIN_URL,
    hugo: "https://themes.gohugo.io/themes/hugo-noir/",
    cnbc: "https://drive.google.com/file/d/1mgHM0do_BvjVAWK2H_XLJJLTOmNzYFbU/view",
  },
};

export const experience = [
  {
    company: "GoodFin",
    role: "AI Engineer Intern",
    shortRole: "AI Engineer",
    date: "2025 · United States",
    shortDate: "2025",
    icon: "finance" as const,
    bullets: [
      "Designed and implemented an end-to-end LLM benchmarking pipeline to evaluate model performance on CFA-level financial tasks using rigorous frameworks and advanced prompting strategies.",
      "Developed a novel AI agent leveraging Graph RAG to tackle complex financial tasks, advancing analytical reasoning, information synthesis, and decision-support capabilities.",
      "Led research on AI adoption in finance ([cfabenchmark.com](https://cfabenchmark.com)), implementing full-cycle data workflows from cleaning extensive JSON benchmark datasets to visualizations and reports.",
    ],
  },
  {
    company: "Marva.ai",
    role: "ML Engineer Intern",
    shortRole: "ML Engineer",
    date: "2023 · India",
    shortDate: "2023",
    icon: "cloud" as const,
    bullets: [
      "Developed financial stock prediction models integrating advanced deep learning techniques",
      "Enhanced buy/sell signal accuracy with hybrid Ichimoku Cloud strategies and refined LSTM models",
      "Leveraged FinBERT and LLM-powered sentiment analysis, boosting stock prediction precision by 20%",
      "Engineered real-time data visualizations using Plotly, Dash, and Streamlit for optimized insights",
    ],
  },
  {
    company: "KSI",
    role: "ML Research Intern",
    shortRole: "ML Researcher",
    date: "2021 · India",
    shortDate: "2021",
    icon: "data" as const,
    bullets: [
      "Designed and deployed a scalable ML pipeline for insurance claim cost prediction",
      "Optimized big data processing with PySpark and Dask, reducing computation time by 50%",
      "Integrated AutoML for hyperparameter tuning, enhancing model performance",
      "Developed interactive dashboards using Power BI and Streamlit for real-time insights",
    ],
  },
];

export const education: { degree: string; field: string; school: string; date: string }[] = [];

// Curated — edit directly in src/data.ts.
export const skills = {
  Languages: [
    { name: "Python", href: "https://www.python.org" },
    { name: "TypeScript", href: "https://www.typescriptlang.org" },
    { name: "JavaScript", href: "https://developer.mozilla.org/en-US/docs/Web/JavaScript" },
    { name: "R", href: "https://www.r-project.org" },
  ],
  "AI / ML": [
    { name: "PyTorch", href: "https://pytorch.org" },
    { name: "LangChain", href: "https://www.langchain.com" },
    { name: "LangGraph", href: "https://www.langchain.com/langgraph" },
    { name: "Hugging Face", href: "https://huggingface.co" },
    { name: "OpenAI", href: "https://openai.com" },
  ],
  Data: [
    { name: "Pandas", href: "https://pandas.pydata.org" },
    { name: "PySpark", href: "https://spark.apache.org/docs/latest/api/python" },
    { name: "MongoDB", href: "https://www.mongodb.com" },
    { name: "Supabase", href: "https://supabase.com" },
  ],
  Web: [
    { name: "React", href: "https://react.dev" },
    { name: "Next.js", href: "https://nextjs.org" },
    { name: "Tailwind CSS", href: "https://tailwindcss.com" },
    { name: "Streamlit", href: "https://streamlit.io" },
    { name: "Flask", href: "https://flask.palletsprojects.com" },
    { name: "Node.js", href: "https://nodejs.org" },
    { name: "Docker", href: "https://www.docker.com" },
    { name: "GitHub", href: "https://github.com" },
  ],
};

// Curated best-5 — edit directly in src/data.ts.
export const projects: {
  name: string;
  description: string;
  href: string;
  icon: "paykit" | "superzed" | "hitch" | "opensec";
  youtube?: string;
}[] = [
  {
    name: "Grok Interviews",
    description:
      "3.6M+ curated interview resources and 81K technical questions across 5 domains — scraped by multi-LLM pipelines over 20+ search engines. Live at grokinterviews.org.",
    href: "https://github.com/prxshetty/grokinterviews",
    icon: "paykit" as const,
    youtube: "https://www.youtube.com/watch?v=bCTKYImpETI",
  },
  {
    name: "Margin",
    description:
      "Local-first AI writing studio for storytellers — markdown-native editor, automatic context from characters and lore, diff review, works with local LLMs or your own agent subscription.",
    href: "https://prxshetty.github.io/margin/",
    icon: "superzed" as const,
    youtube: "https://youtu.be/X18DxQ_3ju8?si=Kv5BRzR_pR2ZQKbl",
  },
  {
    name: "Hugo Noir",
    description:
      "Clean, minimal, multilingual Hugo theme built for readability — picked up 100 stars on GitHub.",
    href: "https://themes.gohugo.io/themes/hugo-noir/",
    icon: "hitch" as const,
  },
  {
    name: "Lumi",
    description:
      "BrickHack runner-up — the first voice-controlled Mac agent: 10 custom tools, real-time speech with interruptions, script execution, web search and image gen, all built from scratch in 24h.",
    href: "https://devpost.com/software/lumi-personal-ai-assistant",
    icon: "opensec" as const,
  },
  {
    name: "Critique",
    description:
      "Lightweight, minimal writing assistant for macOS that runs entirely on-device — Swift, MLX, LLM routing, your own API keys.",
    href: "https://prxshetty.github.io/Critique/",
    icon: "paykit" as const,
  },
];
